kind: pipeline
name: default

steps:
- name: ping
  image: redis
  commands:
  - redis-cli -h cache ping

steps:
- name: docker  
  image: plugins/docker
  settings:
    USERNAME:
      from_secret: DOCKER_USER
    PASSWORD:
      from_secret: DOCKER_PASSWORD
    repo: sai06/flask-drone
    tags:
      - latest
      - '1.0.0'
