kind: pipeline
name: default

steps:
- name: ping
  image: redis
  commands:
  - redis-cli -h cache ping

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: ${DOCKER_USER}
    password: ${DOCKER_PASSWORD}
    tags: latest
