version: '3.6'  
services:  
 app:
   image: sai06/caching:v1
   depends_on:
     - redis
   environment:
     - REDIS_HOST=redis
   ports:
     - "5000:5000"
 redis:
   image: redis:3.2-alpine
   volumes:
     - redis_data:/data
volumes:  
 redis_data:
